# Generated by Django 3.1.7 on 2021-04-02 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210401_2348'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idinput', models.TextField(blank=True, default=None, max_length=50)),
                ('passinput', models.TextField(blank=True, default=None, max_length=50)),
            ],
        ),
    ]
