# Generated by Django 3.1.7 on 2021-04-02 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
