# Generated by Django 3.1.7 on 2021-04-06 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, default=None, max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Account2',
        ),
    ]
