# Generated by Django 3.1.7 on 2021-04-06 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210406_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='account',
        ),
    ]
