# Generated by Django 3.1.7 on 2021-05-24 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_account_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='status',
            field=models.CharField(choices=[('VERIFIED', 'VERIFIED'), ('Not VERIFIED', 'NOT VERIFIED')], max_length=100),
        ),
    ]
